sudo: required
services:
  - docker

before_install:
  - docker build -t ethnopunk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ethnopunk/docker-react npm run test -- --coverage