sudo: required
services:
  - docker

before_install:
  - docker build -t ethnopunk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ethnopunk/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react-bb"
  env: "DockerReactBb-env"
  bucket_name: "elasticbeanstalk-eu-west-1-338430314199"
  bucket_path: "docker-react-bb"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"